### ISSUE TITLE
Detecting Tie in Tictactoe

### ISSUE THREAD

**Issue by SaraGhlm** [alirezagoli/tictactoe#1]
I noticed we do not have any detection for a tie in the game. I will add this feature so that after each move it checks for a tie as well. 
@alirezagoli

**Comment by SaraGhlm** [comment]
I finished the function for checking tie but I have a confusion. Right now the program is able to detect if there is a tie or not and print a message if it is a tie. But the game does not stop after it. In order to stop the program after a tie, I need to change the code in playGame() function in TicTacToeGame.java. I am not sure if this change is part of the feature 3 or 1. Could you please help me to decide where to do it. @alirezagoli

**Comment by alirezagoli** [comment]
@SaraGhlm You can add tie as one of the conditions o stop the game, then in feature 3, we will make the game run to a new board if these conditions are met instead of stopping. @SaraGhlm

**Comment by SaraGhlm** [comment]
I finished the feature 1. I am closing this issue.
